import random
from faker import Faker

health_conditions = [
    "Hypertension",
    "Diabetes",
    "Asthma",
    "Arthritis",
    "Migraine",
    "Depression",
    "Anxiety",
    "Heart disease",
    "Chronic obstructive pulmonary disease (COPD)",
    "Osteoporosis",
    "Alzheimer's disease",
    "Stroke",
    "Cancer",
    "Chronic kidney disease",
    "Epilepsy",
    "Parkinson's disease",
    "Multiple sclerosis",
    "Rheumatoid arthritis",
    "Crohn's disease",
    "Ulcerative colitis",
    "Lupus",
    "Chronic bronchitis",
    "Cataracts",
    "Glaucoma",
    "Hearing loss",
    "Eczema",
    "Psoriasis",
    "Osteoarthritis",
    "Gout",
    "Fibromyalgia",
    "Chronic fatigue syndrome",
    "Sleep apnea",
    "Anemia",
    "Ovarian cysts",
    "Endometriosis",
    "Polycystic ovary syndrome (PCOS)",
    "Hemorrhoids",
    "Gastroesophageal reflux disease (GERD)",
    "Irritable bowel syndrome (IBS)",
    "Chronic sinusitis",
    "Allergies",
    "HIV/AIDS",
    "Thyroid disorders",
    "Hepatitis",
    "Peptic ulcer disease",
    "Interstitial cystitis",
    "Menopause"
]

blood_types = ['A+', 'A-', 'O+', 'O-', 'B+', 'B-', 'AB+', 'AB-']

emergency_medical_events = [
    "Heart attack",
    "Stroke",
    "Cardiac arrest",
    "Severe allergic reaction (Anaphylaxis)",
    "Respiratory distress",
    "Traumatic injury",
    "Burns",
    "Choking",
    "Drowning",
    "Seizures",
    "Unconsciousness",
    "Drug overdose",
    "Suicidal ideation",
    "Major bleeding",
    "Fractures",
    "Head injury",
    "Spinal cord injury",
    "Eye injury",
    "Heatstroke",
    "Hypothermia",
    "Electrocution",
    "Poisoning",
    "Snake bite",
    "Insect bite or sting (Anaphylaxis)",
    "Frostbite",
    "Asthma attack",
    "Diabetic emergency",
    "Severe dehydration",
    "Appendicitis",
    "Gastrointestinal bleeding",
    "Ruptured spleen",
    "Pregnancy complications",
    "Childbirth emergencies",
    "Meningitis",
    "Sepsis",
    "Major allergic reaction (Anaphylaxis)",
    "Severe asthma attack",
    "High fever in infants",
    "Foreign object ingestion",
    "Severe abdominal pain",
    "Severe headache or migraine",
    "Hypoglycemia",
    "Hyperglycemia",
    "Severe abdominal pain",
    "Sudden confusion or disorientation",
    "Severe abdominal pain",
    "Severe back or neck pain"
]

drug_names = [
    "Aspirin",
    "Ibuprofen",
    "Acetaminophen",
    "Lisinopril",
    "Metformin",
    "Simvastatin",
    "Warfarin",
    "Levothyroxine",
    "Metoprolol",
    "Amlodipine",
    "Atorvastatin",
    "Omeprazole",
    "Hydrochlorothiazide",
    "Alprazolam",
    "Sertraline",
    "Citalopram",
    "Fluoxetine",
    "Pantoprazole",
    "Gabapentin",
    "Tramadol",
    "Furosemide",
    "Losartan",
    "Rosuvastatin",
    "Clonazepam",
    "Lorazepam",
    "Escitalopram",
    "Trazodone",
    "Duloxetine",
    "Pregabalin",
    "Metoclopramide",
    "Morphine",
    "Hydromorphone",
    "Codeine",
    "Celecoxib",
    "Naproxen",
    "Ciprofloxacin",
    "Amoxicillin",
    "Methotrexate",
    "Cyclobenzaprine",
    "Diazepam",
    "Mirtazapine",
    "Hydroxyzine",
    "Loratadine",
    "Fluticasone",
    "Montelukast",
    "Methylphenidate",
    "Ranitidine"
]

medical_equipment = [
    "Stethoscope",
    "Blood Pressure Monitor",
    "Electrocardiogram (ECG) Machine",
    "MRI Machine",
    "X-ray Machine",
    "Ultrasound Scanner",
    "Surgical Gloves",
    "Surgical Mask",
    "Scalpel",
    "Sphygmomanometer",
    "Oxygen Mask",
    "Nebulizer",
    "Defibrillator",
    "Pulse Oximeter",
    "Wheelchair",
    "Crutches",
    "Hospital Bed",
    "Ventilator",
    "Autoclave",
    "Surgical Drapes",
    "Anesthesia Machine",
    "Catheter",
    "IV Pole",
    "Surgical Gown",
    "Dental Chair",
    "Glucometer",
    "Tourniquet",
    "Speculum",
    "Ophthalmoscope",
    "Otoscope",
    "Nurse Call System",
    "Fetal Doppler",
    "Orthopedic Cast",
    "Infusion Pump",
    "Surgical Lights",
    "EKG Electrodes",
    "Nasogastric Tube",
    "Cautery Machine",
    "Bone Saw",
    "Laryngoscope",
    "Blood Centrifuge",
    "Phlebotomy Chair",
    "Suction Pump",
    "Cryotherapy Unit",
    "Doppler Ultrasound",
    "Pacemaker",
    "Ambulance Stretcher",
    "Electrosurgical Unit"
]

medical_expertise = [
    "Heimlich Maneuver",
    "Cardiopulmonary Resuscitation (CPR)",
    "First Aid for Burns",
    "Basic Life Support (BLS)",
    "Advanced Cardiovascular Life Support (ACLS)",
    "Trauma Resuscitation",
    "Wound Care",
    "Fracture Splinting",
    "Venipuncture",
    "Intravenous (IV) Cannulation",
    "Urinary Catheterization",
    "EKG Interpretation",
    "Suturing",
    "Airway Management",
    "Emergency Triage",
    "Neonatal Resuscitation",
    "Pulseless Electrical Activity (PEA) Management",
    "Orthopedic Casting",
    "Central Venous Catheterization",
    "Arterial Blood Gas (ABG) Sampling",
    "Intubation",
    "Cricothyrotomy",
    "Spinal Immobilization",
    "Emergency Obstetrics",
    "Pediatric Advanced Life Support (PALS)",
    "Dermatologic Procedures",
    "Advanced Trauma Life Support (ATLS)",
    "Conscious Sedation",
    "Lumbar Puncture",
    "Thoracentesis",
    "Paracentesis",
    "Joint Aspiration",
    "Transcutaneous Pacing",
    "Nasogastric Tube Insertion",
    "Intraosseous Access",
    "Emergency Ultrasound",
    "Emergency Psychiatry",
    "Toxicology Assessment",
    "Disaster Medicine",
    "Hemorrhage Control",
    "Cervical Collar Placement",
    "Hyphema Management",
    "Environmental Emergency Management",
    "Extrication Techniques",
    "Eye Irrigation",
    "Needle Decompression",
    "Triage in Mass Casualty Incidents",
    "Burn Dressing and Management",
    "Emergency Airway Procedures"
]
fake = Faker()


def getRandomSizedSample(inp):
    return random.sample(
        inp,
        random.randint(1, random.randint(1, len(inp)))
    )


def getRandomChoice(inp):
    return fake.random.choice(inp)
